export { buyAction } from './buy.js'
export { checkOnGameoverConditionAction } from './check-on-gameover-condition.js'
export { checkOnWinConditionAction } from './check-on-win-condition.js'
export { deleteGameAction } from './delete-game.js'
export { forwardToNextMonthAction } from './forward-to-next-month.js'
export { loadGameAction } from './load-game.js'
export { loadShipAction } from './load-ship.js'
export { resetAction } from './reset.js'
export { saveGameAction } from './save-game.js'
export { sellAction } from './sell.js'
export { sendShipAction } from './send-ship.js'
export { setColorPreferenceAction } from './set-color-preference.js'
export { setLevelScenarioAction } from './set-level-scenario.js'
export { setPlayernameAction } from './set-playername.js'
export { setTutorialAction } from './set-tutorial.js'
export { switchToCityAction } from './switch-to-city.js'
export { switchToSceneAction } from './switch-to-scene.js'
export { switchToViewAction } from './switch-to-view.js'
export { unloadShipAction } from './unload-ship.js'
export { unveilHistoryAction } from './unveil-history.js'
export { updateShipsAction } from './update-ships.js'

/**
 * @typedef {import('./buy.js').BUY_ACTION | import('./check-on-gameover-condition.js').CHECK_ON_GAMEOVER_CONDITION_ACTION | import('./check-on-win-condition.js').CHECK_ON_WIN_CONDITION_ACTION | import('./delete-game.js').DELETE_GAME_ACTION | import('./forward-to-next-month.js').FORWARD_TO_NEXT_MONTH_ACTION | import('./load-game.js').LOAD_GAME_ACTION | import('./load-ship.js').LOAD_SHIP_ACTION | import('./reset.js').RESET_ACTION | import('./save-game.js').SAVE_GAME_ACTION | import('./sell.js').SELL_ACTION | import('./send-ship.js').SEND_SHIP_ACTION | import('./set-color-preference.js').SET_COLOR_PREFERENCE_ACTION | import('./set-level-scenario.js').SET_LEVEL_SCENARIO_ACTION | import('./set-playername.js').SET_PLAYERNAME_ACTION | import('./set-tutorial.js').SET_TUTORIAL_ACTION | import('./switch-to-city.js').SWITCH_TO_CITY_ACTION | import('./switch-to-scene.js').SWITCH_TO_SCENE_ACTION | import('./switch-to-view.js').SWITCH_TO_VIEW_ACTION | import('./unload-ship.js').UNLOAD_SHIP_ACTION | import('./unveil-history.js').UNVEIL_HISTORY_ACTION | import('./update-ships.js').UPDATE_SHIPS_ACTION} ACTION
 */
